enum UserAccountStatus {
    ACTIVE = 'ACTIVE',
    DISABLED = 'DISABLED',
    EXPIRED = 'EXPIRED',
    PENDING = 'PENDING',
    ACCEPT = 'ACCEPT',
    REJECT = 'REJECT',
    CREATED = 'CREATED',
    COMPLETED = 'COMPLETED',
    PENDING_APPROVAL = 'PENDING_APPROVAL',
    HIDDEN = 'HIDDEN',
    ERROR = 'ERROR'
}
